### ISSUE TITLE
tf_trainer.common.tfrecord_input_test is broken

### ISSUE THREAD

**Issue by sorensenjs** [conversationai/conversationai-models#173]
This test currently fails due to:
Traceback (most recent call last):
  File "/usr/local/google/home/sorenj/github/conversationai-models/experiments/tf_trainer/common/tfrecord_input_test.py", line 75, in test_TFRecordInput_rounded
    round_labels=True)
TypeError: __init__() got an unexpected keyword argument 'feature_preprocessor_init'

but the problem is deeper than just a change in parameter name.

The test begins failing with commit 2a089437ea20bf29782ebf5aeb1f594e33b9789f

**Comment by sorensenjs** [comment]
I'm looking at this, and it seems like I have to bring in text_preprocessor, which needs embeddings. Maybe there's a short cut.

**Comment by fprost** [comment]
Thanks for highlighting it. Looking at it now

**Comment by fprost** [comment]
Update [here](https://github.com/conversationai/conversationai-models/pull/175)
